# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-20 15:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('descricao', models.TextField()),
                ('bloqueado', models.BooleanField(default=False)),
                ('visivel', models.BooleanField(default=True)),
                ('localizacao', models.TextField()),
                ('foto', models.FileField(blank=True, upload_to=b'')),
                ('patrimonio', models.PositiveIntegerField()),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EspacoFisico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('descricao', models.TextField()),
                ('bloqueado', models.BooleanField(default=False)),
                ('visivel', models.BooleanField(default=True)),
                ('localizacao', models.TextField()),
                ('foto', models.FileField(blank=True, upload_to=b'')),
                ('capacidade', models.PositiveSmallIntegerField()),
                ('atividadesPermitidas', models.ManyToManyField(to='agenda.Atividade')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReservaEquipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[(b'A', b'Aprovado'), (b'D', b'Desaprovado'), (b'E', b'Esperando')], default=b'E', max_length=1)),
                ('data', models.DateField()),
                ('horaInicio', models.TimeField()),
                ('horaFim', models.TimeField()),
                ('dataReserva', models.DateTimeField(auto_now_add=True)),
                ('ramal', models.PositiveIntegerField()),
                ('finalidade', models.TextField()),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Atividade')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Equipamento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReservaEspacoFisico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[(b'A', b'Aprovado'), (b'D', b'Desaprovado'), (b'E', b'Esperando')], default=b'E', max_length=1)),
                ('data', models.DateField()),
                ('horaInicio', models.TimeField()),
                ('horaFim', models.TimeField()),
                ('dataReserva', models.DateTimeField(auto_now_add=True)),
                ('ramal', models.PositiveIntegerField()),
                ('finalidade', models.TextField()),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Atividade')),
                ('espacoFisico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.EspacoFisico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=10, unique=True)),
                ('nome', models.TextField()),
                ('descricao', models.TextField()),
                ('logo', models.FileField(blank=True, upload_to=b'')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('unidadePai', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.Unidade')),
            ],
        ),
        migrations.AddField(
            model_name='espacofisico',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Unidade'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Unidade'),
        ),
    ]
