# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='logo',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
