# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-09 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaRecorrente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataInicio', models.DateField(blank=True, null=True)),
                ('dataFim', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='reservaequipamento',
            name='recorrencia',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.ReservaRecorrente'),
        ),
        migrations.AddField(
            model_name='reservaespacofisico',
            name='recorrencia',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.ReservaRecorrente'),
        ),
    ]
