# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-24 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='foto',
            field=models.FileField(blank=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='espacofisico',
            name='foto',
            field=models.FileField(blank=True, upload_to=b''),
        ),
    ]
