# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-06 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='atividadesPermitidas',
            field=models.ManyToManyField(to='agenda.Atividade'),
        ),
    ]
