# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-01 17:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='responsavel',
        ),
        migrations.AddField(
            model_name='equipamento',
            name='responsavel',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='espacofisico',
            name='responsavel',
        ),
        migrations.AddField(
            model_name='espacofisico',
            name='responsavel',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
