# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-17 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaespacofisico',
            name='teste',
            field=models.CharField(default=b'0', max_length=1),
        ),
    ]
