# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-18 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_equipamento_atividadespermitidas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='visivel',
        ),
        migrations.RemoveField(
            model_name='espacofisico',
            name='visivel',
        ),
        migrations.AddField(
            model_name='equipamento',
            name='invisivel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='espacofisico',
            name='invisivel',
            field=models.BooleanField(default=False),
        ),
    ]
