# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-19 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_auto_20180209_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='antecedenciaMaxima',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='antecedenciaMinima',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='espacofisico',
            name='antecedenciaMaxima',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='espacofisico',
            name='antecedenciaMinima',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
