# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-20 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_auto_20171117_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservaespacofisico',
            name='teste',
        ),
    ]
