# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_auto_20170131_1830'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Grupo',
            new_name='Unidade',
        ),
        migrations.RenameField(
            model_name='equipamento',
            old_name='grupo',
            new_name='unidade',
        ),
        migrations.RenameField(
            model_name='espacofisico',
            old_name='grupo',
            new_name='unidade',
        ),
        migrations.RemoveField(
            model_name='reservaequipamento',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='reservaespacofisico',
            name='grupo',
        ),
    ]
