# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-24 21:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_auto_20170624_2106'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Evento',
            new_name='Atividade',
        ),
        migrations.RenameField(
            model_name='espacofisico',
            old_name='eventosPermitidos',
            new_name='atividadesPermitidas',
        ),
        migrations.RenameField(
            model_name='reservaequipamento',
            old_name='evento',
            new_name='atividade',
        ),
        migrations.RenameField(
            model_name='reservaespacofisico',
            old_name='evento',
            new_name='atividade',
        ),
    ]
