# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_auto_20170223_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unidade',
            old_name='grupoPai',
            new_name='unidadePai',
        ),
    ]
