# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-08 16:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_auto_20180219_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='espacofisico',
            options={'verbose_name': 'Espa\xe7o f\xedsico', 'verbose_name_plural': 'Espa\xe7os f\xedsicos'},
        ),
        migrations.AlterModelOptions(
            name='reservaespacofisico',
            options={'verbose_name': 'Reserva espa\xe7o f\xedsico', 'verbose_name_plural': 'Reservas espa\xe7os f\xedsicos'},
        ),
        migrations.AddField(
            model_name='equipamento',
            name='permissaoNecessaria',
            field=models.BooleanField(default=False, verbose_name=b'Reservar somente com autoriza\xc3\xa7\xc3\xa3o do respons\xc3\xa1vel'),
        ),
        migrations.AddField(
            model_name='espacofisico',
            name='permissaoNecessaria',
            field=models.BooleanField(default=False, verbose_name=b'Reservar somente com autoriza\xc3\xa7\xc3\xa3o do respons\xc3\xa1vel'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='descricao',
            field=models.TextField(verbose_name=b'Descri\xc3\xa7\xc3\xa3o'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='antecedenciaMaxima',
            field=models.PositiveIntegerField(default=0, verbose_name=b'Anteced\xc3\xaancia m\xc3\xadnima'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='antecedenciaMinima',
            field=models.PositiveSmallIntegerField(default=0, verbose_name=b'Anteced\xc3\xaancia m\xc3\xa1xima'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='atividadesPermitidas',
            field=models.ManyToManyField(to='agenda.Atividade', verbose_name=b'Atividades permitidas'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='descricao',
            field=models.TextField(verbose_name=b'Descri\xc3\xa7\xc3\xa3o'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='fotoLink',
            field=models.URLField(blank=True, verbose_name=b'Link para foto'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='grupos',
            field=models.ManyToManyField(blank=True, to='auth.Group', verbose_name=b'Grupos que podem reservar automaticamente'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='invisivel',
            field=models.BooleanField(default=False, verbose_name=b'Invis\xc3\xadvel'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='localizacao',
            field=models.TextField(verbose_name=b'Localiza\xc3\xa7\xc3\xa3o'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='patrimonio',
            field=models.PositiveIntegerField(verbose_name=b'Patrim\xc3\xb4nio'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='responsavel',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name=b'Respons\xc3\xa1veis'),
        ),
        migrations.AlterField(
            model_name='espacofisico',
            name='antecedenciaMaxima',
            field=models.PositiveIntegerField(default=0, verbose_name=b'Anteced\xc3\xaancia m\xc3\xadnima'),
        ),
        migrations.AlterField(
            model_name='espacofisico',
            name='antecedenciaMinima',
            field=models.PositiveSmallIntegerField(default=0, verbose_name=b'Anteced\xc3\xaancia m\xc3\xa1xima'),
        ),
        migrations.AlterField(
            model_name='espacofisico',
            name='atividadesPermitidas',
            field=models.ManyToManyField(to='agenda.Atividade', verbose_name=b'Atividades permitidas'),
        ),
        migrations.AlterField(
            model_name='espacofisico',
            name='descricao',
            field=models.TextField(verbose_name=b'Descri\xc3\xa7\xc3\xa3o'),
        ),
        migrations.AlterField(
            model_name='espacofisico',
            name='fotoLink',
            field=models.URLField(blank=True, verbose_name=b'Link para foto'),
        ),
        migrations.AlterField(
            model_name='espacofisico',
            name='grupos',
            field=models.ManyToManyField(blank=True, to='auth.Group', verbose_name=b'Grupos que podem reservar automaticamente'),
        ),
        migrations.AlterField(
            model_name='espacofisico',
            name='invisivel',
            field=models.BooleanField(default=False, verbose_name=b'Invis\xc3\xadvel'),
        ),
        migrations.AlterField(
            model_name='espacofisico',
            name='localizacao',
            field=models.TextField(verbose_name=b'Localiza\xc3\xa7\xc3\xa3o'),
        ),
        migrations.AlterField(
            model_name='espacofisico',
            name='responsavel',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name=b'Respons\xc3\xa1veis'),
        ),
        migrations.AlterField(
            model_name='reservaequipamento',
            name='horaFim',
            field=models.TimeField(verbose_name=b'Hora fim'),
        ),
        migrations.AlterField(
            model_name='reservaequipamento',
            name='horaInicio',
            field=models.TimeField(verbose_name=b'Hora in\xc3\xadcio'),
        ),
        migrations.AlterField(
            model_name='reservaequipamento',
            name='locavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Equipamento', verbose_name=b'Loc\xc3\xa1vel'),
        ),
        migrations.AlterField(
            model_name='reservaequipamento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Usu\xc3\xa1rio'),
        ),
        migrations.AlterField(
            model_name='reservaespacofisico',
            name='horaFim',
            field=models.TimeField(verbose_name=b'Hora fim'),
        ),
        migrations.AlterField(
            model_name='reservaespacofisico',
            name='horaInicio',
            field=models.TimeField(verbose_name=b'Hora in\xc3\xadcio'),
        ),
        migrations.AlterField(
            model_name='reservaespacofisico',
            name='locavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.EspacoFisico', verbose_name=b'Loc\xc3\xa1vel'),
        ),
        migrations.AlterField(
            model_name='reservaespacofisico',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Usu\xc3\xa1rio'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='descricao',
            field=models.TextField(verbose_name=b'Descri\xc3\xa7\xc3\xa3o'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='logoLink',
            field=models.URLField(blank=True, verbose_name=b'Link para a logo'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='responsavel',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name=b'Respons\xc3\xa1veis'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='unidadePai',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.Unidade', verbose_name=b'Unidade pai'),
        ),
    ]
