# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-22 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_remove_reservaespacofisico_teste'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='espacofisico',
            name='foto',
        ),
        migrations.AddField(
            model_name='equipamento',
            name='fotoLink',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='espacofisico',
            name='fotoLink',
            field=models.URLField(blank=True),
        ),
    ]
