# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-24 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_auto_20170624_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='visivel',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='espacofisico',
            name='visivel',
            field=models.BooleanField(default=True),
        ),
    ]
