# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-03 15:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agenda', '0003_auto_20171101_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.RemoveField(
            model_name='unidade',
            name='responsavel',
        ),
        migrations.AddField(
            model_name='unidade',
            name='responsavel',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
