# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-24 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_auto_20170624_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaequipamento',
            name='estado',
            field=models.CharField(choices=[(b'A', b'Aprovado'), (b'D', b'Desaprovado'), (b'E', b'Esperando')], max_length=1),
        ),
        migrations.AlterField(
            model_name='reservaespacofisico',
            name='estado',
            field=models.CharField(choices=[(b'A', b'Aprovado'), (b'D', b'Desaprovado'), (b'E', b'Esperando')], max_length=1),
        ),
    ]
