# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-22 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_auto_20171122_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidade',
            name='logo',
        ),
        migrations.AddField(
            model_name='unidade',
            name='logoLink',
            field=models.URLField(blank=True),
        ),
    ]
