# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-16 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_auto_20171103_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='unidade',
            name='sigla',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
