# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-08 20:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agenda', '0004_auto_20180308_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[(b'A', b'Aprovado'), (b'D', b'Desaprovado'), (b'E', b'Esperando')], default=b'E', max_length=1)),
                ('data', models.DateField()),
                ('horaInicio', models.TimeField(verbose_name=b'Hora in\xc3\xadcio')),
                ('horaFim', models.TimeField(verbose_name=b'Hora fim')),
                ('dataReserva', models.DateTimeField(auto_now_add=True)),
                ('ramal', models.PositiveIntegerField()),
                ('finalidade', models.TextField()),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Atividade')),
            ],
            options={
                'verbose_name': 'Reserva servi\xe7o',
                'verbose_name_plural': 'Reserva servi\xe7os',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('descricao', models.TextField(verbose_name=b'Descri\xc3\xa7\xc3\xa3o')),
                ('bloqueado', models.BooleanField(default=False)),
                ('invisivel', models.BooleanField(default=False, verbose_name=b'Invis\xc3\xadvel')),
                ('permissaoNecessaria', models.BooleanField(default=False, verbose_name=b'Reservar somente com autoriza\xc3\xa7\xc3\xa3o de um respons\xc3\xa1vel')),
                ('antecedenciaMinima', models.PositiveSmallIntegerField(default=0, verbose_name=b'Anteced\xc3\xaancia m\xc3\xa1xima')),
                ('antecedenciaMaxima', models.PositiveIntegerField(default=0, verbose_name=b'Anteced\xc3\xaancia m\xc3\xadnima')),
                ('localizacao', models.TextField(verbose_name=b'Localiza\xc3\xa7\xc3\xa3o')),
                ('fotoLink', models.URLField(blank=True, verbose_name=b'Link para foto')),
                ('atividadesPermitidas', models.ManyToManyField(to='agenda.Atividade', verbose_name=b'Atividades permitidas')),
                ('grupos', models.ManyToManyField(blank=True, to='auth.Group', verbose_name=b'Grupos que podem reservar automaticamente')),
                ('profissionais', models.ManyToManyField(related_name='profissionais', to=settings.AUTH_USER_MODEL, verbose_name=b'Profissionais que executam o servi\xc3\xa7o')),
                ('responsavel', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name=b'Respons\xc3\xa1veis')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Unidade')),
            ],
            options={
                'verbose_name': 'Servi\xe7o',
                'verbose_name_plural': 'Servi\xe7os',
            },
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='permissaoNecessaria',
            field=models.BooleanField(default=False, verbose_name=b'Reservar somente com autoriza\xc3\xa7\xc3\xa3o de um respons\xc3\xa1vel'),
        ),
        migrations.AlterField(
            model_name='espacofisico',
            name='permissaoNecessaria',
            field=models.BooleanField(default=False, verbose_name=b'Reservar somente com autoriza\xc3\xa7\xc3\xa3o de um respons\xc3\xa1vel'),
        ),
        migrations.AddField(
            model_name='reservaservico',
            name='locavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Servico', verbose_name=b'Loc\xc3\xa1vel'),
        ),
        migrations.AddField(
            model_name='reservaservico',
            name='recorrencia',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.ReservaRecorrente'),
        ),
        migrations.AddField(
            model_name='reservaservico',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Usu\xc3\xa1rio'),
        ),
    ]
