# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-20 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_auto_20171220_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='grupos',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='espacofisico',
            name='grupos',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='grupos',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
    ]
