# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-20 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_auto_20180308_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='somenteGrupo',
            field=models.BooleanField(default=False, verbose_name=b'Apenas membros do grupo podem pedir reserva'),
        ),
        migrations.AddField(
            model_name='espacofisico',
            name='somenteGrupo',
            field=models.BooleanField(default=False, verbose_name=b'Apenas membros do grupo podem pedir reserva'),
        ),
        migrations.AddField(
            model_name='servico',
            name='somenteGrupo',
            field=models.BooleanField(default=False, verbose_name=b'Apenas membros do grupo podem pedir reserva'),
        ),
    ]
