# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-22 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_auto_20180320_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaequipamento',
            name='estado',
            field=models.CharField(choices=[(b'A', b'Aprovado'), (b'D', b'Desaprovado'), (b'E', b'Esperando'), (b'C', b'Cancelado')], default=b'E', max_length=1),
        ),
        migrations.AlterField(
            model_name='reservaespacofisico',
            name='estado',
            field=models.CharField(choices=[(b'A', b'Aprovado'), (b'D', b'Desaprovado'), (b'E', b'Esperando'), (b'C', b'Cancelado')], default=b'E', max_length=1),
        ),
        migrations.AlterField(
            model_name='reservaservico',
            name='estado',
            field=models.CharField(choices=[(b'A', b'Aprovado'), (b'D', b'Desaprovado'), (b'E', b'Esperando'), (b'C', b'Cancelado')], default=b'E', max_length=1),
        ),
    ]
