# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-21 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_auto_20170808_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservaequipamento',
            old_name='espacoFisico',
            new_name='equipamento',
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='foto',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='espacofisico',
            name='foto',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='reservaequipamento',
            name='estado',
            field=models.CharField(choices=[('A', 'Aprovado'), ('D', 'Desaprovado'), ('E', 'Esperando')], default='E', max_length=1),
        ),
        migrations.AlterField(
            model_name='reservaespacofisico',
            name='estado',
            field=models.CharField(choices=[('A', 'Aprovado'), ('D', 'Desaprovado'), ('E', 'Esperando')], default='E', max_length=1),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='logo',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
