# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-21 16:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agenda', '0008_auto_20180410_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=32)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de recupera\xe7\xe3o',
                'verbose_name_plural': 'Tokens de recupera\xe7\xe3o',
            },
        ),
    ]
