# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-23 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_recoverytoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoverytoken',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
