# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-04 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0010_recoverytoken_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='limite_horas',
            field=models.TimeField(null=True, verbose_name=b'Limite de Horas por Usu\xc3\xa1rio'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='periodo_limite',
            field=models.IntegerField(null=True),
        ),
    ]
