# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-08 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0014_auto_20190410_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaequipamento',
            name='locavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agenda.Equipamento', verbose_name=b'Equipamento'),
        ),
        migrations.AlterField(
            model_name='reservaservico',
            name='locavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agenda.Servico', verbose_name=b'Servi\xc3\xa7o'),
        ),
    ]
